triton_store_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: TritonStoreBundle:Default:index }

triton_store_create:
    pattern:  /create/
    defaults: { _controller: TritonStoreBundle:Default:create }

triton_store_show_by_id:
    pattern:  /show/{id}
    defaults: { _controller: TritonStoreBundle:Default:show }
    requirements:
        id:  \d+

triton_store_show:
    pattern:  /show/all
    defaults: { _controller: TritonStoreBundle:Default:showAll }

triton_store_show_price:
    pattern:  /show/price
    defaults: { _controller: TritonStoreBundle:Default:showPrice }

triton_store_new:
    pattern:  /new
    defaults: { _controller: TritonStoreBundle:Default:new }

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin
    
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin   