parameters:
#    triton_store.example.class: Triton\StoreBundle\Example

services:
#    triton_store.example:
#        class: %triton_store.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
